#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-responses
Version  : 0.19.0
Release  : 41
URL      : https://files.pythonhosted.org/packages/37/b8/5e550b9b5b05778e38f1bdf12d7e7718502e6d0719b09f812fcc84829058/responses-0.19.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/37/b8/5e550b9b5b05778e38f1bdf12d7e7718502e6d0719b09f812fcc84829058/responses-0.19.0.tar.gz
Summary  : A utility library for mocking out the `requests` Python library.
Group    : Development/Tools
License  : Apache-2.0
Requires: pypi-responses-license = %{version}-%{release}
Requires: pypi-responses-python = %{version}-%{release}
Requires: pypi-responses-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(coverage)
BuildRequires : pypi(flake8)
BuildRequires : pypi(pytest)
BuildRequires : pypi(pytest_cov)
BuildRequires : pypi(pytest_localserver)
BuildRequires : pypi(requests)
BuildRequires : pypi(urllib3)
BuildRequires : pypi(werkzeug)
BuildRequires : pypi-pytest

%description
Responses
=========
.. image:: https://img.shields.io/pypi/v/responses.svg
:target: https://pypi.python.org/pypi/responses/

%package license
Summary: license components for the pypi-responses package.
Group: Default

%description license
license components for the pypi-responses package.


%package python
Summary: python components for the pypi-responses package.
Group: Default
Requires: pypi-responses-python3 = %{version}-%{release}

%description python
python components for the pypi-responses package.


%package python3
Summary: python3 components for the pypi-responses package.
Group: Default
Requires: python3-core
Provides: pypi(responses)
Requires: pypi(requests)
Requires: pypi(urllib3)

%description python3
python3 components for the pypi-responses package.


%prep
%setup -q -n responses-0.19.0
cd %{_builddir}/responses-0.19.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1646664723
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
pytest
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-responses
cp %{_builddir}/responses-0.19.0/LICENSE %{buildroot}/usr/share/package-licenses/pypi-responses/cef33b64c628a8301c7f0a1d2360484b9fe5bed1
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-responses/cef33b64c628a8301c7f0a1d2360484b9fe5bed1

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
